ALTER TABLE sys_role MODIFY id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE sys_oper_log MODIFY id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE sys_config MODIFY id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE sys_dict MODIFY id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE sys_menu MODIFY id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE sys_role_menu MODIFY id BIGINT NOT NULL AUTO_INCREMENT;